name: Dagger CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install Dagger
      run: curl -L https://dl.dagger.io/dagger/install.sh | sh
    - name: Run Dagger Pipeline
      run: go run ci/pipeline.go